# -*- coding: utf-8 -*-
"""Assignment_1 (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fF0bUErAJwMlPwGJ8sWNQvNth-Twwf7L

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

a=s.split()
print(a)

"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

txt="The diameter of {planet} is {diameter} kilometers".format(planet="Earth",diameter=12742)
print(txt)

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

print(d['k1'][3]["tricky"][3]['target'][3])

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

a=np.zeros(10)
print(a)

b=np.ones(10)*5
print(b)

"""## 5. Create an array of all the even integers from 20 to 35"""

c=np.arange(20,35,2)
print(c)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

d=np.arange(9).reshape(3,3)
print(d)

"""## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

data=[['tom',10],['jerry',15],['spike',14]]
df=pd.DataFrame(data,columns=['Name','Age'])
print(df)

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

dt1=pd.datetime(2023,2,10)
dt2=pd.datetime(2023,1,1)
dt3=dt1-dt2
print(dt3)

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

df=pd.DataFrame(lists)
print(df)